/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:83c81b44-35d4-4049-833b-e63be0e0e10a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3ubq46OPS",
    "aws_user_pools_web_client_id": "54goe3pe219piitk8vl7nimiu9",
    "oauth": {}
};


export default awsmobile;
